default:
  image: beagle/debian-build

build-on-amd64:
  stage: build
  tags:
    - docker-amd64-ci
  script:
    - make package
    - mkdir public
    - cp ../librobotcontrol_*.deb public/
  artifacts:
    paths:
      - public

build-on-aarch64:
  stage: build
  tags:
    - docker-aarch64-ci
  script:
    - make package
    - mkdir public
    - cp ../librobotcontrol_*.deb public/
  artifacts:
    paths:
      - public

build-on-riscv64:
  image: beagle/ubuntu-build
  stage: build
  tags:
    - docker-riscv64-ci
  script:
    - make package
    - mkdir public
    - cp ../librobotcontrol_*.deb public/
  artifacts:
    paths:
      - public

build-on-armv7:
  image: beagle/ubuntu-build
  stage: build
  tags:
    - docker-armhf-ci
  script:
    - make package
    - mkdir public
    - cp ../librobotcontrol_*.deb public/
  artifacts:
    paths:
      - public
