build:
  stage: build
  parallel:
    matrix:
      - IMAGE: debian-build
        TAG: [docker-amd64, docker-aarch64-ci, docker-armhf]
      - IMAGE: ubuntu-build
        TAG: [docker-riscv64-ci]
  image: beagle/${IMAGE}
  tags:
    - ${TAG}
  script:
    - make package
    - mkdir public
    - cp ../librobotcontrol_*.deb public/
  artifacts:
    paths:
      - public
