image: beagle/debian-build

build-on-amd64:
  stage: build
  tags:
    - docker-amd64
  script:
    - make package
  artifacts:
    paths:
      - ../librobotcontrol_*.deb

build-on-aarch64:
  stage: build
  tags:
    - docker-aarch64
  script:
    - make package
    - mkdir public
    - cp ../librobotcontrol_*.deb public/
  artifacts:
    paths:
      - public
