image: beagle/debian-build

build-on-amd64:
  stage: build
  tags:
    - docker-amd64
  script:
    - make package
  artifacts:
    paths:
      - ../librobotcontrol_*.deb

build-on-aarch64:
  stage: build
  tags:
    - docker-aarch64
  script:
    - make package
    - mkdir public
    - cp ../librobotcontrol_*.deb public/
  artifacts:
    paths:
      - public

# run tests using the binary built
test:
  stage: test
  before_script:
    - apt update && apt -y install gnupg ca-certificates
    - apt-key adv --batch --keyserver keyserver.ubuntu.com --recv-key D284E608A4C46402
    - echo "deb [arch=arm64] http://debian.beagle.cc/arm64/ bullseye main" >> /etc/apt/sources.list
    - apt update && apt -y install make bb-customizations
  script:
    - dpkg -i build/librobotcontrol_*_arm64.deb
    - make test
