image: debian:bullseye

build:
  stage: build
  before_script:
    - apt update && apt -y install gnupg ca-certificates
    - apt-key adv --batch --keyserver keyserver.ubuntu.com --recv-key D284E608A4C46402
    - echo "deb [arch=arm64] http://debian.beagle.cc/arm64/ bullseye main" >> /etc/apt/sources.list
    - apt update && apt -y install gcc make build-essential ti-pru-cgt-v2.3 ti-pru-software devscripts debhelper debconf
  script:
    - make package
    - mkdir -p build
    - mv ../librobotcontrol_* build/
  artifacts:
    paths:
      - build/*

# run tests using the binary built before
test:
  stage: test
  script:
    - make test

