build:
  stage: build
  parallel:
    matrix:
      - IMAGE: bookworm
        TAG: [docker-amd64, docker-aarch64-ci, docker-armhf]
          #- IMAGE: noble
          #TAG: [docker-riscv64-ci]
  image: registry.git.beagleboard.org/jkridner/debian-build:${IMAGE}
  tags:
    - ${TAG}
  script:
    - make package
    - mkdir -p public/pkg/${IMAGE}
    - cp ../librobotcontrol_*.deb public/pkg/${IMAGE}
  artifacts:
    paths:
      - public

pages:
  image: registry.git.beagleboard.org/jkridner/debian-build:latest
  stage: deploy
  dependencies:
    - "build: [bookworm, docker-amd64]"
    - "build: [bookworm, docker-aarch64-ci]"
    - "build: [bookworm, docker-armhf]"
      #- "build: [noble, docker-riscv64-ci]"
  before_script:
    - apt-get update && apt-get install -y doxygen
  script:
    - cd public/pkg
    - apindex
    - cd ../../docs
    - doxygen
    - cp -R html/* ../public/
  artifacts:
    paths:
      - public

