image: beagle/debian-builds

build-on-amd64:
  stage: build
  tags:
    - docker-amd64
  before_script:
    - apt-get update
    - apt-get -o APT::Install-Suggests="true" install -y devscripts
  script:
    - make package
  artifacts:
    paths:
      - ../librobotcontrol_*.deb

build-on-aarch64:
  stage: build
  tags:
    - docker-aarch64
  before_script:
    - apt-get update
    - apt-get -o APT::Install-Suggests="true" install -y devscripts
  script:
    - make package
  artifacts:
    paths:
      - ../librobotcontrol_*.deb
